name: Python Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout du code source
      - name: Checkout code
        uses: actions/checkout@v4

      # Configuration de Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      # Installation de pip et pytest
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest  # Installe pytest

      # Exécution des tests avec pytest
      - name: Run tests with pytest
        run: |
          pytest  # Exécute pytest
