name: Python Tests

on:
  push:
    branches:
      - master  # Déclenche l'action sur la branche master
  pull_request:
    branches:
      - master  # Déclenche l'action lors des pull requests sur la branche master

jobs:
  test:
    runs-on: ubuntu-latest  # Utilise l'environnement Ubuntu pour exécuter les tests

    steps:
      # Étape 1 : Checkout du code source
      - name: Checkout code
        uses: actions/checkout@v4  # Utilisation de la version mise à jour de actions/checkout

      # Étape 2 : Configuration de Python
      - name: Set up Python
        uses: actions/setup-python@v5  # Utilisation de la version mise à jour de actions/setup-python
        with:
          python-version: '3.x'  # Remplacez par la version Python souhaitée

      # Étape 3 : Installation des dépendances
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Assurez-vous d'avoir un fichier requirements.txt

      # Étape 4 : Exécution des tests avec pytest
      - name: Run tests with pytest
        run: |
          pytest  # Exécute les tests dans le projet
