name: Python Tests

on:
  push:
    branches:
      - master  # Assurez-vous que la branche spécifiée est 'master'
  pull_request:
    branches:
      - master  # Assurez-vous que la branche spécifiée est 'master'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Remplacez par la version Python désirée

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with pytest
        run: |
          pytest
